<?php
include_once('includes/verify.php');
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>untitled</title>	
</head>

<body>
	<h1>This is a secure page.</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique pulvinar urna, et pulvinar velit elementum sit amet. Phasellus laoreet mattis convallis. Vestibulum elit nunc, pulvinar non tempor vitae, molestie a leo. Aliquam lacinia ac urna nec eleifend. Duis interdum orci purus, in commodo diam tempus vitae. Suspendisse eget pharetra nunc. Vestibulum ac nisi leo. Mauris nec pretium felis. Quisque faucibus, leo id fringilla gravida, arcu libero dapibus erat, quis sodales purus massa eget urna.</p>
	<p>Mauris ullamcorper massa sed nisi laoreet porta dictum quis diam. Aliquam vulputate tristique augue a venenatis. Proin vitae velit sed odio egestas tristique vitae vitae velit. Pellentesque sodales interdum est quis tempus. Aliquam ut gravida enim. Suspendisse libero velit, feugiat non feugiat molestie, accumsan at diam. Maecenas id urna vehicula, tristique erat sit amet, congue ante. Fusce et vehicula massa.</p>
	<p>Nullam facilisis turpis tellus, quis egestas mi tempus id. Vivamus blandit turpis sed volutpat rutrum. Curabitur egestas, arcu id consequat ornare, massa ipsum pulvinar orci, et faucibus neque massa vitae mi. Pellentesque quis mi eget orci interdum feugiat eu id felis. Praesent in magna ut lorem sodales fermentum consequat sit amet enim. Suspendisse nec mauris id nisl lobortis sollicitudin ac sed tortor. Donec auctor, magna vitae volutpat semper, turpis eros vestibulum arcu, scelerisque facilisis massa orci sit amet erat. Phasellus tristique, nisl vitae feugiat euismod, orci justo consectetur quam, nec tincidunt justo ipsum vulputate est. Nunc leo dui, dapibus pretium blandit quis, luctus et nibh. Mauris lacinia mi ante, et malesuada lacus sagittis nec. Quisque porta neque libero, vel fermentum orci volutpat nec. Donec pellentesque cursus risus placerat pulvinar. Aenean eget dolor magna. Vestibulum ultrices ac libero sed sodales.</p>
	<p>Cras porta suscipit pellentesque. Aliquam lobortis turpis ut massa dictum, eget volutpat nulla aliquam. Nam consectetur nulla eu mauris tincidunt, at faucibus ipsum accumsan. Fusce quis pretium quam. Sed ut enim et enim posuere congue. Praesent quis libero placerat, tempor enim ut, pretium odio. Sed porta ante vel porta suscipit. Nunc consequat, orci nec cursus tincidunt, ipsum ipsum porttitor elit, in euismod purus mauris ullamcorper ligula. Proin ac sapien ante. Praesent mattis ipsum mi, non fringilla ligula viverra vel. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc tempus luctus magna consectetur ullamcorper. Fusce venenatis tempor lectus a lobortis.</p>
	<p>Morbi ut augue quis dui imperdiet mollis. Vestibulum ac tincidunt metus, quis scelerisque est. Vestibulum molestie dui sit amet congue iaculis. Vestibulum adipiscing dignissim nibh nec pharetra. Nullam fermentum tristique lorem vel blandit. Aenean convallis lorem dui, ut tempor nulla vehicula lobortis. Sed malesuada massa ac velit iaculis bibendum. Nunc ut magna vitae sapien commodo gravida sed at lectus. In eu lorem ultrices, ultrices tellus vel, consequat sem. Donec quam neque, vehicula vel consequat non, varius vitae libero. Nullam ut dui in turpis tempor sollicitudin. Duis vel nunc sed tellus tristique dignissim. Donec interdum ligula sed lectus euismod porttitor. Praesent sem lacus, interdum vel dolor ac, dapibus pellentesque purus. Phasellus mollis, felis quis eleifend aliquam, risus nisi hendrerit massa, eget congue quam mi non arcu. Nullam sed urna mi.</p>
	<p>Vivamus nec arcu nunc. Praesent metus metus, accumsan id pharetra in, feugiat eget diam. Aliquam laoreet accumsan rhoncus. Sed pulvinar gravida metus, et mattis orci posuere id. Fusce nibh elit, dapibus sed dictum ut, sodales sed lacus. Nulla scelerisque orci magna, id bibendum augue posuere iaculis. Pellentesque lobortis posuere congue.</p>
	<p>Vestibulum elementum, erat consequat aliquam dictum, lectus tortor sollicitudin ipsum, eu congue felis tortor eget tortor. In accumsan tincidunt orci, bibendum mollis enim vestibulum ac. Mauris vulputate dui a mollis dignissim. Integer sit amet consequat neque. Morbi auctor non leo ac blandit. Praesent venenatis dignissim vulputate. Aenean nibh enim, venenatis lacinia hendrerit id, cursus id purus. Suspendisse ultricies pharetra libero sed egestas. Morbi tempus tincidunt hendrerit. Duis velit arcu, elementum at sapien a, dapibus aliquet odio. Vestibulum dictum risus in massa luctus tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
</body>
</html>
